/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */
#include "CallbackProxy.h"

//static fields
jclass CallbackProxy::sClazz = nullptr;
jmethodID CallbackProxy::sConstruct_0 = nullptr;
jmethodID CallbackProxy::sConstruct_1 = nullptr;
jmethodID CallbackProxy::sConstruct_2 = nullptr;
jmethodID CallbackProxy::sMethod_onJobStart_0 = nullptr;
jmethodID CallbackProxy::sMethod_onJobStart_1 = nullptr;
jmethodID CallbackProxy::sMethod_onJobDone_2 = nullptr;
jmethodID CallbackProxy::sMethod_onJobProgress_3 = nullptr;
jfieldID CallbackProxy::sField_ANOTHER_COMPILE_CONSTANT_INT_0 = nullptr;
jfieldID CallbackProxy::sField_count_1 = nullptr;
jfieldID CallbackProxy::sField_staticName_2 = nullptr;
jfieldID CallbackProxy::sField_aStaticField_3 = nullptr;
jfieldID CallbackProxy::sField_name_4 = nullptr;
jfieldID CallbackProxy::sField_lock_5 = nullptr;
jfieldID CallbackProxy::sField_staticCount_6 = nullptr;


