/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */
#include "NestedClassProxy.h"

//static fields
jclass NestedClassProxy::sClazz = nullptr;
jmethodID NestedClassProxy::sConstruct_0 = nullptr;
jmethodID NestedClassProxy::sMethod_hello_0 = nullptr;


