/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */

/* C++ header file for class com.young.jennysampleapp.ComputeIntensiveClass */
#pragma once

#include <jni.h>



#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_young_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass
 * Method:    public java.util.HashMap<java.lang.String,java.lang.String> one(java.lang.String param)
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject Java_com_young_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_one(JNIEnv *env, jobject thiz, jstring param);


/*
 * Class:     com_young_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass
 * Method:    public long nativeInit()
 * Signature: ()J
 */
JNIEXPORT jlong Java_com_young_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_nativeInit(JNIEnv *env, jobject thiz);


/*
 * Class:     com_young_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass
 * Method:    public void nativeRelease(long handle)
 * Signature: (J)V
 */
JNIEXPORT void Java_com_young_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_nativeRelease(JNIEnv *env, jobject thiz, jlong handle);


#ifdef __cplusplus
}
#endif


