/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */
#include "${header}"

${android_log_marcos}
//java class name: ${full_java_class_name}
static constexpr auto FULL_CLASS_NAME = "${full_slash_class_name}";
#define constants(cons) ${full_native_class_name}_ ## cons

//change to whatever you like
static constexpr auto LOG_TAG  = "${simple_class_name}";

${methods}

${dynamic_jni_register}

${jni_onload_impl}
