/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */
#include "ComputeInNative.h"




/*
 * Class:     io_github_landerlyoung_jennysample_ComputeInNative
 * Method:    public boolean init()
 * Signature: ()Z
 */
jboolean ComputeInNative::init(JNIEnv *env, jobject thiz) {
    return JNI_FALSE;
}

/*
 * Class:     io_github_landerlyoung_jennysample_ComputeInNative
 * Method:    public void release()
 * Signature: ()V
 */
void ComputeInNative::release(JNIEnv *env, jobject thiz) {
    return;
}

/*
 * Class:     io_github_landerlyoung_jennysample_ComputeInNative
 * Method:    public void setParam(java.util.Map<java.lang.String,java.lang.String> globalHttpParam)
 * Signature: (Ljava/util/Map;)V
 */
void ComputeInNative::setParam(JNIEnv *env, jobject thiz, jobject globalHttpParam) {
    return;
}

/*
 * Class:     io_github_landerlyoung_jennysample_ComputeInNative
 * Method:    public java.util.Map<java.lang.String,java.lang.String> getGlobalParam()
 * Signature: ()Ljava/util/Map;
 */
jobject ComputeInNative::getGlobalParam(JNIEnv *env, jobject thiz) {
    return nullptr;
}

/*
 * Class:     io_github_landerlyoung_jennysample_ComputeInNative
 * Method:    public boolean request(java.lang.String json, io.github.landerlyoung.jennysample.RequestListener listener)
 * Signature: (Ljava/lang/String;Lio/github/landerlyoung/jennysample/RequestListener;)Z
 */
jboolean ComputeInNative::request(JNIEnv *env, jobject thiz, jstring json, jobject listener) {
    return JNI_FALSE;
}




