/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */
#include "RequestListenerProxy.h"

//static fields
jclass RequestListenerProxy::sClazz = nullptr;
jmethodID RequestListenerProxy::sMethod_onResponse_0 = nullptr;


