/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#pragma once

#include <jni.h>

#include "CallbackProxy.h"
#include "GenericProxy.h"
#include "NativeDrawableProxy.h"
#include "NestedClassProxy.h"
#include "android_RectProxy.h"
#include "android_StyleProxy.h"
#include "java_lang_RuntimeExceptionProxy.h"
#include "java_okhttp_BuilderProxy.h"
#include "java_okhttp_CallProxy.h"
#include "java_okhttp_OkHttpClientProxy.h"
#include "java_okhttp_RequestProxy.h"
#include "java_okhttp_ResponseBodyProxy.h"
#include "java_okhttp_ResponseProxy.h"
#include "jenny_GraphicsProxy.h"

namespace jenny {

inline bool initAllProxies(JNIEnv* env) {

   bool success = 
        ::CallbackProxy::initClazz(env) &&
        ::GenericProxy::initClazz(env) &&
        ::NativeDrawableProxy::initClazz(env) &&
        ::NestedClassProxy::initClazz(env) &&
        android::RectProxy::initClazz(env) &&
        android::StyleProxy::initClazz(env) &&
        java::lang::RuntimeExceptionProxy::initClazz(env) &&
        java::okhttp::BuilderProxy::initClazz(env) &&
        java::okhttp::CallProxy::initClazz(env) &&
        java::okhttp::OkHttpClientProxy::initClazz(env) &&
        java::okhttp::RequestProxy::initClazz(env) &&
        java::okhttp::ResponseBodyProxy::initClazz(env) &&
        java::okhttp::ResponseProxy::initClazz(env) &&
        jenny::GraphicsProxy::initClazz(env);
   return success;
}

} // end of namespace jenny
