/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#pragma once

#include <jni.h>
#include <assert.h>                        
#include <atomic>
#include <mutex>

#include "jnihelper.h"


class NestedClassProxy {

public:
    static constexpr auto FULL_CLASS_NAME = "io/github/landerlyoung/jennysampleapp/Callback$NestedClass";



public:

    static bool initClazz(JNIEnv* env);
    
    static void releaseClazz(JNIEnv* env);

    static void assertInited(JNIEnv* env) {
        auto initClazzSuccess = initClazz(env);
        assert(initClazzSuccess);
    }
    
    // construct: public NestedClass()
    static jobject newInstance(JNIEnv* env, jobject enclosingClass) {
       assertInited(env);
       return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_0, enclosingClass);
    } 
    

    // method: public void hello()
    static void hello(JNIEnv* env, jobject thiz, jobject enclosingClass) {
        assertInited(env);
        env->CallVoidMethod(thiz, getClassInitState().sMethod_hello_0, enclosingClass);
    }


    // ====== jni helper ======
private:
   ::jenny::LocalRef<jobject> _local;
   ::jenny::GlobalRef<jobject> _global;
 
public:

   // jni helper
   jobject getThis() const { return _local ? _local.get() : _global.get(); }

   // jni helper constructors
   NestedClassProxy(jobject ref, bool owned = false): _local(ref, owned) {}
   
   NestedClassProxy(::jenny::LocalRef<jobject> ref): _local(std::move(ref)) {}
   
   NestedClassProxy(::jenny::GlobalRef<jobject> ref): _global(std::move(ref)) {}
   
    // construct: public NestedClass()
    static NestedClassProxy newInstance(jobject enclosingClass) {
       ::jenny::Env env; assertInited(env.get());
       return env->NewObject(getClassInitState().sClazz, getClassInitState().sConstruct_0, enclosingClass);
    } 
    

    // for jni helper
    // method: public void hello()
    void hello(jobject enclosingClass) const {
        ::jenny::Env env; jobject thiz = getThis();
        env->CallVoidMethod(thiz, getClassInitState().sMethod_hello_0, enclosingClass);
    }



private:
    struct ClassInitState {
    // thread safe init
    std::atomic_bool sInited {};
    std::mutex sInitLock {};

    jclass sClazz = nullptr;
    jmethodID sConstruct_0 = nullptr;

    jmethodID sMethod_hello_0 = nullptr;


   }; // endof struct ClassInitState

   static inline ClassInitState& getClassInitState() {
       static ClassInitState classInitState;
       return classInitState;
   }

};





// external logger function passed by jenny.errorLoggerFunction
void jennySampleErrorLog(JNIEnv* env, const char* error);



/*static*/ inline bool NestedClassProxy::initClazz(JNIEnv* env) {
#define JENNY_CHECK_NULL(val)                      \
       do {                                        \
           if ((val) == nullptr) {                 \
               jennySampleErrorLog(env, "can't init NestedClassProxy::" #val); \
               return false;                       \
           }                                       \
       } while(false)

    auto& state = getClassInitState();
    if (!state.sInited) {
        std::lock_guard<std::mutex> lg(state.sInitLock);
        if (!state.sInited) {
            auto clazz = env->FindClass(FULL_CLASS_NAME);
            JENNY_CHECK_NULL(clazz);
            state.sClazz = reinterpret_cast<jclass>(env->NewGlobalRef(clazz));
            env->DeleteLocalRef(clazz);
            JENNY_CHECK_NULL(state.sClazz);

            state.sConstruct_0 = env->GetMethodID(state.sClazz, "<init>", "(Lio/github/landerlyoung/jennysampleapp/Callback;)V");
            JENNY_CHECK_NULL(state.sConstruct_0);


            state.sMethod_hello_0 = env->GetMethodID(state.sClazz, "hello", "()V");
            JENNY_CHECK_NULL(state.sMethod_hello_0);



            state.sInited = true;
        }
    }
#undef JENNY_CHECK_NULL
   return true;
}

/*static*/ inline void NestedClassProxy::releaseClazz(JNIEnv* env) {
    auto& state = getClassInitState();
    if (state.sInited) {
        std::lock_guard<std::mutex> lg(state.sInitLock);
        if (state.sInited) {
            env->DeleteGlobalRef(state.sClazz);
            state.sClazz = nullptr;
            state.sInited = false;
        }
    }
}



