/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

/* C++ header file for class io/github/landerlyoung/jennysampleapp/ComputeIntensiveClass$NestedNativeClass */
#pragma once

#include <jni.h>


namespace NestedNativeClass {

// DO NOT modify
static constexpr auto FULL_CLASS_NAME = u8"io/github/landerlyoung/jennysampleapp/ComputeIntensiveClass$NestedNativeClass";

static constexpr jint CONST = 0;


} // endof namespace NestedNativeClass



#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public java.util.HashMap<java.lang.String,java.lang.String> one(java.lang.String param)
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_one(JNIEnv* env, jobject thiz, jstring param);

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public long nativeInit()
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_nativeInit(JNIEnv* env, jobject thiz);

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void testOverload()
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_testOverload__(JNIEnv* env, jobject thiz);

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void testOverload(java.lang.Object o)
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_testOverload__Ljava_lang_Object_2(JNIEnv* env, jobject thiz, jobject o);

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void nativeRelease(long handle)
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_nativeRelease(JNIEnv* env, jobject thiz, jlong handle);

#ifdef __cplusplus
}
#endif