/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */
#include "NestedNativeClass.h"

/*
 * Class:     io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass
 * Method:    public java.util.HashMap<java.lang.String,java.lang.String> one(java.lang.String param)
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
jobject Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_one(JNIEnv *env, jobject thiz, jstring param) {
    return nullptr;
}

/*
 * Class:     io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass
 * Method:    public long nativeInit()
 * Signature: ()J
 */
jlong Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_nativeInit(JNIEnv *env, jobject thiz) {
    return 0;
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void testOverload()
 * Signature: ()V
 */
void Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_testOverload__(JNIEnv *env, jobject thiz) {

}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.ComputeIntensiveClass$NestedNativeClass
 * Method:    public void testOverload(java.lang.Object o)
 * Signature: (Ljava/lang/Object;)V
 */
void Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_testOverload__Ljava_lang_Object_2(JNIEnv *env, jobject thiz, jobject o) {

}

/*
 * Class:     io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass
 * Method:    public void nativeRelease(long handle)
 * Signature: (J)V
 */
void Java_io_github_landerlyoung_jennysampleapp_ComputeIntensiveClass_00024NestedNativeClass_nativeRelease(JNIEnv *env, jobject thiz, jlong handle) {
    return;
}

