/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#include "NativeDrawable.h"




/*
 * Class:     io.github.landerlyoung.jennysampleapp.NativeDrawable
 * Method:    private final long nativeInit()
 * Signature: ()J
 */
jlong NativeDrawable::nativeInit(JNIEnv* env, jobject thiz) {
    // TODO(jenny): generated method stub.
    return 0;
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.NativeDrawable
 * Method:    public final void onClick()
 * Signature: ()V
 */
void NativeDrawable::onClick(JNIEnv* env, jobject thiz) {
    // TODO(jenny): generated method stub.
    
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.NativeDrawable
 * Method:    public void draw(android.graphics.Canvas canvas)
 * Signature: (Landroid/graphics/Canvas;)V
 */
void NativeDrawable::draw(JNIEnv* env, jobject thiz, jobject canvas) {
    // TODO(jenny): generated method stub.
    
}

/*
 * Class:     io.github.landerlyoung.jennysampleapp.NativeDrawable
 * Method:    public final void release()
 * Signature: ()V
 */
void NativeDrawable::release(JNIEnv* env, jobject thiz) {
    // TODO(jenny): generated method stub.
    
}




