name: Android CI

on:
  pull_request:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Build :sample-android with Gradle
      run: |
        ./gradlew :sample-android:assembleDebug
    - name: Test incremental compile
      run: |
        echo "// test incremental compile" >> sample-android/src/main/java/io/github/landerlyoung/jennysampleapp/Callback.java
        ./gradlew :sample-android:assembleDebug
    - name: Test :sample-java
      run: |
        ./run_sample_java_test
